### PR TITLE
Adding simple indentation formatting to Strings files

### PR DESCRIPTION
**Pull request by powtac**

### CODE REVIEW

**Comment by netbe** [comment]
@powtac I removed support for 1.9.4, still have to fix style issues. 
Also I don't see how the indentation is changed from config file. Or is it always 0?

**Comment by powtac** [comment]
I did not realize that there is a configuration file. The "0" just indicates to not indent = default. How much to indent will be calculated for each file dynamically.

**Comment by netbe** [comment]
@powtac ok I understand then it's fine. Remaining is style see @houndci comments.

**Comment by powtac** [comment]
Some of the houndci recommendations are independent from my changes, the "problems" were already in the code. See the "return" notices? Should I fix them as well?

**Comment by netbe** [comment]
If you don't mind, yep, but there s no rush I don t know when i will
release again

On Wednesday, March 18, 2015, Simon Brüchner <notifications@github.com>
wrote:

> Some of the houndci recommendations are independent from my changes, the
> "problems" were already in the code. See the "return" notices? Should I fix
> them as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netbe/Babelish/pull/50#issuecomment-83046182>.
>


-- 
*François Benaiteau*
Phone:  +49 152 04062600
Skype:  be_net
Twitter:  http://twitter.com/netbeatwork <http://twitter.com/netbeatwork>
LinkedIn:  http://fr.linkedin.com/in/benaiteau
Github:  https://github.com/netbe

**Comment by powtac** [comment]
I would like to not do that. Because I'm not a Ruby Programmer so I'm really having a hard time to do everything right. :-/

**Comment by netbe** [comment]
Closing in favor of #63

**Pull request closed without merging**
